### ISSUE TITLE
Change title color of the toolbar

### ISSUE THREAD

**Issue by fgnm** [MFlisar/GDPRDialog#91] opened 2020-02-05 21:20 UTC
I've just update the material library to stable 1.1.0, and the toolbar of the GDPRDialog changed. The color it's nice, but I'm not able to change the color of the title.
Here is an image:
![Screen toolbar](https://user-images.githubusercontent.com/5543339/73884155-919b6b00-4865-11ea-9b22-68c8a026ea7f.png)

I would like to have the title with white color.

**Comment by 1951FDG** [comment] 2020-02-11 13:22
Are you using ```withNoToolbarTheme(true)``` ? I recommend you set this to false.

**Comment by fgnm** [comment] 2020-02-20 09:24
No, I'm not using `withNoToolbarTheme(true)`

**Comment by 1951FDG** [comment] 2020-02-20 19:19
Are you using latest version ```implementation 'com.github.MFlisar:GDPRDialog:1.4.2'``` ?
Are you using BottomSheetDialogFragment ?

**Comment by fgnm** [comment] 2020-02-20 19:26
Yes, I'm using the latest version `implementation 'com.github.MFlisar:GDPRDialog:1.4.2'`. This is my init code:
```Java
mGDPRSetupetup = new GDPRSetup(GDPRDefinitions.ADMOB, GDPRDefinitions.FIREBASE_ANALYTICS, GDPRDefinitions.FABRIC_CRASHLYTICS, GDPRDefinitions.FABRIC_ANSWERS)
                .withAllowNoConsent(false)
                .withExplicitAgeConfirmation(false)
                .withCheckRequestLocation(GDPRLocationCheck.DEFAULT)
                .withBottomSheet(true)
                .withForceSelection(true)
                .withShortQuestion(true)
                .withPrivacyPolicy("...url...")
                .withLoadAdMobNetworks("...id...");
        GDPR.getInstance().checkIfNeedsToBeShown(this, mGDPRSetupetup);
```

This behaviour has appear after upgrade to latest stable of the material library `implementation 'com.google.android.material:material:1.1.0'`

As I can see [here](https://github.com/MFlisar/GDPRDialog/blob/1bf865049a6a8c359575ee0a7b8e12d12fb5244c/versions.gradle#L12) this library still uses 1.0.0

**Comment by 1951FDG** [comment] 2020-02-20 20:24
Add:
```
.withCustomDialogTheme(R.style.ThemeOverlay_MaterialComponents_BottomSheetDialog_Custom)
```

Add custom style to styles.xml:
```
<style name="ThemeOverlay.MaterialComponents.BottomSheetDialog.Custom" parent="ThemeOverlay.MaterialComponents.BottomSheetDialog">
        <item name="titleTextColor">@android:color/white</item>
</style>
```

**Comment by fgnm** [comment] 2020-02-21 12:05
It does not work, I've tried to do so:
```XML
<style name="ThemeOverlay.MaterialComponents.BottomSheetDialog.Custom" parent="ThemeOverlay.MaterialComponents.BottomSheetDialog">
    <item name="android:textColorPrimary">@android:color/white</item>
    <item name="android:textColor">@android:color/black</item>
</style>
```
And I've got the desired result. However is a bit tricky as method, maybe could be used a cleaner way.

**Comment by 1951FDG** [comment] 2020-02-24 09:04
Another way is overwriting the resource in your app:
https://github.com/MFlisar/GDPRDialog/blob/master/library/src/main/res/layout/gdpr_dialog.xml

Can't decide on if this qualifies as a cleaner way, but it does allow you to apply a style or theme to the toolbar directly.

**Comment by MFlisar** [comment] 2020-03-25 16:57
Sorry for the late reply.

I updated the versions in the demo app and used some custom colors in the demo app - can you reproduce your issue in the demo as well?

Generally make sure you use a `Theme.MaterialComponents.*` theme, the library only works with them.

**Comment by MFlisar** [comment] 2020-07-20 06:42
closing because there is no communication anymore

**Closed by MFlisar** 2020-07-20 06:42 UTC
